name: Deploy AdonisJS (MySQL) to Azure

on:
  push:
    branches:
      - deploy-to-azure
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          cd app-flashcards
          npm install

      - name: Build Adonis
        run: |
          cd app-flashcards
          npm run build

      - name: Prepare deploy folder
        run: |
          mkdir deploy
          cp -R app-flashcards/build deploy/build
          cp app-flashcards/package.json deploy/
          cp app-flashcards/package-lock.json deploy/

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: FlashCards-maenau
          slot-name: Production
          package: deploy
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CBFBDF400E01439496E91FE3263A5615 }}
